In [62]:
import pandas as pd
import os
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# import nltk
#
# nltk.download('stopwords')
# nltk.download('punkt')
#nltk.download('punkt_tab')

In [63]:
# CSV file called combined_data.csv
for filename in os.listdir('./CSV Data'):
    print(filename)
    for file in os.listdir(f'./CSV Data/{filename}'):
        if file.endswith('.csv'):
            df = pd.read_csv(f'./CSV Data/{filename}/{file}')
            new_df = df[['Issue Type', 'Status', 'Priority', 'Summary', 'Original Time Estimated', 'Total Time Spent']].copy()
            new_df = new_df[:-1]
            new_df['Summary'] = new_df['Summary'].str.replace(r'WS-\d+', '', regex=True)
            new_df['Summary'] = new_df['Summary'].str.replace(r'PALM-\d+', '', regex=True)
            new_df['Summary'] = new_df['Summary'].str.replace(r'APO-\d+', '', regex=True)
            new_df['Summary'] = new_df['Summary'].str.replace(r'MED-\d+', '', regex=True)
            new_df['Summary'] = new_df['Summary'].str.replace(r'[^\w\s]', '', regex=True)
            new_df['Issue Type'] = new_df['Issue Type'].str.replace(r'[^\w\s]', '', regex=True)
            # add header if the file doesn't exist yet
            if not os.path.isfile('./Cleaned Data/combined_data.csv'):
                new_df.to_csv('./Cleaned Data/combined_data.csv', mode='a', header=True, index=False)
            else:
                new_df.to_csv('./Cleaned Data/combined_data.csv', mode='a', header=False, index=False)

weos data
med AI
Apollo
Marritime
PALM

In [64]:
# load cleaned data into a dataframe
project_df = pd.read_csv('./Cleaned Data/combined_data.csv')

In [65]:
project_df

,Issue Type,Status,Priority,Summary,Original Time Estimated,Total Time Spent
0,Bug,Done,Blocker,When an integration has the option to setup su...,-,30m
1,Bug,Done,Major,Getting a null error response when first loadi...,-,1h 5m
2,Story,Done,Critical,I should be able to setup a Finance assistant,-,0m
3,Task,Done,Major,UI Cleanup,-,-
4,Story,Done,Critical,When my session expires I should be taken to l...,1h,1h
...,...,...,...,...,...,...
13190,Subtask,Done,Major,setup account domain object and gorm model,-,-
13191,Subtask,Done,Major,Add screen for editing a bill,-,-
13192,Subtask,Done,Major,add screen for listing schedules,-,-
13193,Subtask,Done,Major,Add view screen for categorie that shows items,-,-
13194,Subtask,Done,Major,remove previous email that was being sent,-,-

In [66]:
# remove all the records with the total timespent is empty ie '-'
project_df = project_df[project_df['Total Time Spent'] != '-']

In [21]:
# remove all the records with the original time estimated is empty ie '-'
#project_df = project_df[project_df['Original Time Estimated'] != '-']

In [67]:
project_df.describe()

,Issue Type,Status,Priority,Summary,Original Time Estimated,Total Time Spent
count,10297,10297,10241,10297,10297,10297
unique,6,10,4,1427,27,295
top,Subtask,Done,Major,Feedback,-,1h
freq,6874,9408,9219,203,4242,1561

In [68]:
def to_minutes(time_str: str, hours_per_day: int = 8) -> int:
    total_minutes = 0

    # Split the input string by spaces
    parts = time_str.split()

    for part in parts:
        if part.endswith('d'):
            num = float(part[:-1])
            total_minutes += num * hours_per_day * 60
        elif part.endswith('h'):
            num = float(part[:-1])
            total_minutes += num * 60
        elif part.endswith('m'):
            num = float(part[:-1])
            total_minutes += num

    return int(total_minutes)

In [69]:
project_df['Total Time Spent'] = project_df['Total Time Spent'].apply(to_minutes)

/var/folders/sr/38b34mxn0m74n_l9f9hpfmjc0000gp/T/ipykernel_3317/1350899843.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  project_df['Total Time Spent'] = project_df['Total Time Spent'].apply(to_minutes)

In [70]:
project_df['Original Time Estimated'] = project_df['Original Time Estimated'].apply(to_minutes)

/var/folders/sr/38b34mxn0m74n_l9f9hpfmjc0000gp/T/ipykernel_3317/3448611759.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  project_df['Original Time Estimated'] = project_df['Original Time Estimated'].apply(to_minutes)

In [71]:
project_df

,Issue Type,Status,Priority,Summary,Original Time Estimated,Total Time Spent
0,Bug,Done,Blocker,When an integration has the option to setup su...,0,30
1,Bug,Done,Major,Getting a null error response when first loadi...,0,65
2,Story,Done,Critical,I should be able to setup a Finance assistant,0,0
4,Story,Done,Critical,When my session expires I should be taken to l...,60,60
5,Bug,Done,Major,All the connections are deleted when a blank c...,0,105
...,...,...,...,...,...,...
13180,Subtask,Done,Major,Add a form for creating a vendor item,120,60
13181,Subtask,Done,Major,Add command receiver and endpoint for creati...,120,60
13182,Subtask,In Progress,Major,Update the expense form to show list of rela...,120,390
13183,Subtask,Done,Major,Add form for editing invoice,120,40
13185,Subtask,Done,Major,Hook up editing vendor quote screen,60,60

In [72]:
# Removing additional white spaces and punctuation to make the text uniform
project_df['Summary'] = project_df['Summary'].str.replace(r'[^\w\s]', '', regex=True)

/var/folders/sr/38b34mxn0m74n_l9f9hpfmjc0000gp/T/ipykernel_3317/1374567763.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  project_df['Summary'] = project_df['Summary'].str.replace(r'[^\w\s]', '', regex=True)

In [73]:
# Remove special characters from the summary column
project_df['Summary'] = project_df['Summary'].str.replace(r'WS-\d+', '', regex=True)

/var/folders/sr/38b34mxn0m74n_l9f9hpfmjc0000gp/T/ipykernel_3317/1600985738.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  project_df['Summary'] = project_df['Summary'].str.replace(r'WS-\d+', '', regex=True)

In [74]:
stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    words = text.split()
    filtered_words = [word for word in words if word not in stop_words]
    return ' '.join(filtered_words)

In [75]:
project_df['Summary'] = project_df['Summary'].apply(remove_stopwords)

/var/folders/sr/38b34mxn0m74n_l9f9hpfmjc0000gp/T/ipykernel_3317/1633645839.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  project_df['Summary'] = project_df['Summary'].apply(remove_stopwords)

In [78]:
# tokenize the summary column
project_df['Summary'] = project_df['Summary'].apply(word_tokenize)

/var/folders/sr/38b34mxn0m74n_l9f9hpfmjc0000gp/T/ipykernel_3317/1121015393.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  project_df['Summary'] = project_df['Summary'].apply(word_tokenize)

In [79]:
project_df

,Issue Type,Status,Priority,Summary,Original Time Estimated,Total Time Spent
0,Bug,Done,Blocker,"[When, integration, option, setup, sub, resour...",0,30
1,Bug,Done,Major,"[Getting, null, error, response, first, loadin...",0,65
2,Story,Done,Critical,"[I, able, setup, Finance, assistant]",0,0
4,Story,Done,Critical,"[When, session, expires, I, taken, login]",60,60
5,Bug,Done,Major,"[All, connections, deleted, blank, connection,...",0,105
...,...,...,...,...,...,...
13180,Subtask,Done,Major,"[Add, form, creating, vendor, item]",120,60
13181,Subtask,Done,Major,"[Add, command, receiver, endpoint, creating, v...",120,60
13182,Subtask,In Progress,Major,"[Update, expense, form, show, list, related, v...",120,390
13183,Subtask,Done,Major,"[Add, form, editing, invoice]",120,40
13185,Subtask,Done,Major,"[Hook, editing, vendor, quote, screen]",60,60

In [80]:
# Store the cleaned data into a new CSV file
project_df.to_csv('./Cleaned Data/cleaned_data.csv', index=False)